# Generated by Django 4.2.2 on 2023-07-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Tech', 'Tech'), ('Tools', 'Tools'), ('Toys', 'Toys')], default='', max_length=9),
        ),
    ]
