# Generated by Django 4.2.2 on 2023-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_discription_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_start',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
