# Generated by Django 4.2.2 on 2023-07-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_list_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='list_user',
        ),
    ]
