# Generated by Django 4.2.2 on 2023-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='list_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
