# Generated by Django 4.2.2 on 2023-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='list_pic',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
