# Generated by Django 4.2.2 on 2023-07-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_list_pic_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_user',
            new_name='user',
        ),
    ]
