# Generated by Django 4.2.2 on 2023-07-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_list_user_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='list_user',
        ),
    ]
