# Generated by Django 4.2.2 on 2023-07-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_user_listing_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
    ]
