# Generated by Django 4.2.2 on 2023-07-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
