# Generated by Django 4.2.2 on 2023-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_bid_current_alter_bids_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_user',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
