# Generated by Django 4.2.2 on 2023-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_bids_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_comment',
            field=models.CharField(max_length=64),
        ),
    ]
