# Generated by Django 4.2.2 on 2023-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_comments_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='list_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
