# Generated by Django 3.2.12 on 2023-07-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_list_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='item_comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
