# Generated by Django 4.2.2 on 2023-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_list',
            name='watching',
            field=models.BooleanField(default=False),
        ),
    ]
