# Generated by Django 4.2.2 on 2023-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_watch_list_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_list',
            name='watching',
            field=models.BooleanField(default=False, verbose_name='Watch List'),
        ),
    ]
